### ISSUE TITLE
Jekyll v4.3 Not Displaying Staff Names Correctly

### ISSUE THREAD

**Issue by Vrownie** [UCLA-CS-131/fall-22#8]
It seems that the class website is recently upgraded to Jekyll v4.3.0, and there is a [known bug](https://github.com/jekyll/jekyll/issues/9164) in this version that causes the `name` field to not be interpreted correctly. This causes the [staff page](https://ucla-cs-131.github.io/fall-22/staff/) to render incorrectly. 

I was able to resolve this issue locally with a simple replacement of the `name` field to something else (such as `staff_name`), and updating `_layouts/staffer.html` respectively. I imagine that this can also be solved with the new version v4.3.1 which includes the bug fix for this issue.

**Comment by mattxwang** [comment]
Really appreciate you taking the time to look into the problem, submit an issue, and open a PR! That's awesome, keep it up :))
